version: '3.8'
services:
  app:
    image: dipanshuhappy/email_verifier_tee:1.0.0
    container_name: app
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      - PORT=${PORT}
      - RESEND_API=${RESEND_API}
    restart: always
