[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# RPC endpoints
[rpc_endpoints]
base_sepolia = "https://base-sepolia.drpc.org"
sepolia = "https://rpc.sepolia.org"
horizen_testnet = "https://horizen-rpc-testnet.appchain.base.org"

# Etherscan configuration for contract verification
[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
